version: "3.8"
services:
  backend:
    build: ./obi-back             # path to Dockerfile
    container_name: obi-back-c    # name of docker container
    ports:
      - "5000:3000"               # mapped ports: "local:docker"
    volumes:
      - ./obi-back:/app           # mapped files: "local:docker"
      - /app/node_modules         # mapped (locked) files: "docker"
    environment:
      - PORT=3000                 # env variable "name=value"
  frontend:
    build: ./obi-front
    container_name: obi-front-c
    ports:
      - "3000:3000"
    volumes:
      - ./obi-front:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - VITE_PORT=3000
      - VITE_SERVER_URL=http://localhost:5000